# Generated by Django 4.1.1 on 2022-09-23 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="제목")),
                ("content", models.CharField(max_length=500, verbose_name="내용")),
                ("hashtags", models.CharField(max_length=100, verbose_name="해쉬태그")),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
                (
                    "views",
                    models.PositiveSmallIntegerField(default=0, verbose_name="조회수"),
                ),
                (
                    "create_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성일"),
                ),
                (
                    "update_date",
                    models.DateTimeField(auto_now=True, verbose_name="수저일"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
