# Generated by Django 4.1.1 on 2022-09-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0002_hashtags_remove_post_hashtags_alter_post_update_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="hashtags",
            field=models.ManyToManyField(null=True, to="post.hashtags"),
        ),
    ]
